In [90]:
#Create a NumPy array from a Python list [5, 10, 15, 20, 25] and print its type.
import numpy as np
l=[5, 10, 15, 20, 25]
arr= np.array(l)
arr
#or
arr=np.asarray(l)
arr=np.asanyarray(l)


In [23]:
#Generate an array of 10 random integers between 1 and 100 using NumPy.
import random
arr=np.random.randint(1,100 ,size=10)
arr

array([28, 58, 57, 71, 93, 62, 83, 60, 80, 44], dtype=int32)

In [31]:
#Create a 1D array of numbers from 0 to 50 with a step size of 5.
arr1=np.arange(0,50,5)
arr1

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45])

In [39]:
#Create a 3×3 identity matrix using NumPy
arr2=np.eye(3,3)
arr2.ndim

2

In [59]:
#Create a NumPy array of shape (4,4) filled with random floating-point numbers between 0 and 1.
import numpy as np
import random
arr3= np.random.rand(16).reshape(4,4)
arr3

array([[0.01371131, 0.0193334 , 0.03961551, 0.76481209],
       [0.04967091, 0.23117724, 0.91558569, 0.35321547],
       [0.22624705, 0.18485256, 0.70167134, 0.72510661],
       [0.55268569, 0.37529617, 0.97382167, 0.6707937 ]])

In [72]:
#Generate an array of 20 zeros and another of 20 ones.
arr4=np.zeros(20)
arr5=np.ones(20)

In [78]:
#Create an array of 10 elements and set the fifth element to 99.
arr=np.array([1,2,3,4,5,6,7,8,9,10])
arr[4]=18
arr


array([ 1,  2,  3,  4, 18,  6,  7,  8,  9, 10])

In [79]:
#Reshape the given 1D array into a 2D array with shape (3, 2):
arr = np.array([1, 2, 3, 4, 5, 6])
arr.reshape(3,2)
arr

array([[1, 2],
       [3, 4],
       [5, 6]])

In [87]:
arr = np.array([[10, 20, 30], [40, 50, 60]])
#flatten the array
print(arr.reshape(6,))
#or we can
print(arr.flatten())

[10 20 30 40 50 60]
[10 20 30 40 50 60]


In [93]:
#Stack two arrays horizontally and vertically.
a1=np.array([1,2,3])
a2=np.array([4,5,6])
st1= np.hstack((a1,a2))
st2= np.vstack((a1,a2))
print(st1)
print(st2)

[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]


In [106]:
#Split the given NumPy array into four equal parts.
arr1=np.array([10, 20, 30, 40, 50, 60, 70, 80])
print(arr1[0:int(len(arr1)/4)])
print(arr1[int(len(arr1)/4):int(len(arr1)/2)])
print(arr1[int(len(arr1)/2):3*int(len(arr1)/4)])
print(arr1[3*int(len(arr1)/4):len(arr1)])
#or
print(np.split(arr1,4))

[10 20]
[30 40]
[50 60]
[70 80]
[array([10, 20]), array([30, 40]), array([50, 60]), array([70, 80])]


In [112]:
#Extract all numbers greater than 50 from the array.
arr = np.array([12, 55, 23, 67, 45, 89, 34])
arr[arr>50]

array([55, 67, 89])

In [122]:
#13. Replace all even numbers in an array with -1.
arr = np.array([10, 15, 22, 35, 40, 55])
arr[arr%2==0]=-1
arr
#or
result = np.where(arr % 2 == 0, -1, arr)

In [123]:
###14. Reverse the order of elements in a NumPy array.
arr = np.array([1, 2, 3, 4, 5, 6])
arr[::-1]


array([6, 5, 4, 3, 2, 1])

In [127]:
#Find the maximum, minimum, and mean of the given array:
arr = np.array([100, 200, 50, 75, 150, 250])
print(np.max(arr),np.min(arr),np.mean(arr))

250 50 137.5


In [129]:
#Compute the sum of all rows and columns of the given matrix:
matrix = np.array([[5, 10, 15], [20, 25, 30], [35, 40, 45]])
print(np.sum(matrix,axis=0))
print(np.sum(matrix,axis=1))


[60 75 90]
[ 30  75 120]


In [132]:
#17. Find the dot product of two matrices.
a=np.array([[1, 2], [3, 4]]) 
b=np.array([[5, 6], [7, 8]])
print(a@b)




[[19 22]
 [43 50]]


In [133]:
#Perform element-wise multiplication between two NumPy arrays
a = np.array([1, 3, 5])
b = np.array([2, 4, 6])
print(a*b)

[ 2 12 30]


In [156]:
# Sort an array in ascending and descending order.
arr=np.array([15, 3, 9, 1, 7, 12])
print(np.sort(arr))
print(np.sort(arr)[::-1],type(np.sort(arr)[::-1]))
#np.sort will return numpy class and sorted will return list classv


[ 1  3  7  9 12 15]
[15 12  9  7  3  1] <class 'numpy.ndarray'>


In [163]:
#find std and variance
data = np.array([10, 20, 30, 40, 50, 60, 70])
print(np.std(data,dtype=float))
print(np.var(data,dtype=float))

20.0
400.0
